### PR TITLE
Run view should show COPY/PUBLIC/PRIVATE tags

### LINKED ISSUE #26: [View > Metadata] "Copy" tag is missing for copied Tales
**Steps to Reproduce**
1. Deploy and register LIGO Tale
1. *Tale Dashboard* > *Public Tales*: click "Run Tale" on "LIGO Tutorial" and click "Confirm"
1. *Tale Dashboard* > *My Tales*: click on "View" on "LIGO Tutorial" (your copy)

**Expected Results**
The fact that it's a copy of a Tale is indicated somewhere (in the header?)

**Actual Results**
No indication that we're operating on a copy.

### LINKED ISSUE #27: Copy on Launch dialog doesn't "run" the Tale
**Steps to Reproduce**
1. Deploy and register LIGO
1. *Tale Dashboard* > *Public Tales*: click "Run Tale" on "LIGO Tutorial" and click "Confirm"

**Expected Results**
Tale is copied and launched.

**Actual Results**
Tale is just copied.

**NOTES**
While I'm completely fine with that behavior (and it's my personal preference) I don't know if we collectively agreed on changing that. Either way the wording on the modal should be updated (now it's suggesting launch) or the Tale has to actually launch.

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
1. On creating a Tale copy, user is not brought to the new Tale's Run view
2. Fixes #27 - `copy-on-launch-modal` appears to indicate that it will *run* the Tale, when it does not
3. Fixes #26  - There is no indication that a particular Tale was copied from another Tale.

## Approach
Per the [mockups](https://whole-tale.github.io/wholetale-css-mockup/src/run.html):
1. Navigate the user to the new Tale when creating a copy, as we currently do for Create or Launch
2. Adjusted the text on the `copy-on-launch-modal` to better indicate that this operation will not actually Run the Tale
3. Added a `COPY` tag to the header of the Run view, also added the missing `PUBLIC` / `PRIVATE` indicators as well

## How to Test
Prerequisites: LIGO Tale

1. Checkout this branch locally, rebuild the dashboard
2. Login to the WholeTale Dashboard
3. Navigate to the Public Tales Catalog
4. Find the LIGO Tale and choose "Run Tale"
    * You should be prompted to create a copy
    * You should notice that this modal has had its text updated to say "create a writeable copy" instead of "run a writeable copy"
5. Confirm to create a copy
    * You should automatically be navigated to your new Tale copy's Run view
    * You should see the Run view's header has had some font/styling adjustments, and should more closely match the mockups
    * You should see that the author(s) now appears to the right of the Tale title
    * You should see the `COPY` and `PRIVATE` tags below your Tale's title

### CODE REVIEW

**Comment by Xarthisius** [comment]
Trying to build this PR yields:

```
ERROR in src/app/tales/components/tale-run-button/tale-run-button.component.ts(164,46): error TS2345: Argument of type 'Tale' is not assignable to parameter of type '{ tale: Tale; instance: Instance; }'.
  Type 'Tale' is missing the following properties from type '{ tale: Tale; instance: Instance; }': tale, instance
```

**Comment by bodom0015** [comment]
This was likely a bad merge fix... I should have been more careful and tested after fixing the conflicts.

Apologies, I will go ahead and retest this to fix the bad merges/behavior there
